--Start using the SUBASHAGENCIES Database
USE SUBASHAGENCIES

-- Drop CUSTOMERCATEGORY table to recreate it.
DROP TABLE CUSTOMER_CATEGORY;

--Create CUSTOMERCATEGORY table.
CREATE TABLE CUSTOMER_CATEGORY(
CATEGORYID INT IDENTITY(1,1),
CATEGORYNAME VARCHAR(MAX) NOT NULL,
UPDATED_ON DATE
CONSTRAINT PK_CUSTOMER_CATEGORY_CATEGORYID PRIMARY KEY CLUSTERED (CATEGORYID));

-- Insert records into CUSTOMERCATEGORY table.
INSERT INTO CUSTOMER_CATEGORY(CATEGORYNAME) VALUES ('WHOLESALE');
INSERT INTO CUSTOMER_CATEGORY(CATEGORYNAME) VALUES ('RETAIL');

-- Show the inserted records.
SELECT * FROM CUSTOMER_CATEGORY;