CREATE TABLE CUSTOMERCITY(
CITYID INT IDENTITY(1,1),
CITYNAME VARCHAR(MAX) NOT NULL,
PINCODE VARCHAR(MAX) NOT NULL,
CONSTRAINT PK_CUSTOMERCITY_CITYID PRIMARY KEY CLUSTERED (CITYID));

--DROP TABLE CUSTOMERCITY;

INSERT INTO CUSTOMERCITY (CITYNAME, PINCODE) VALUES ('TOWN1','500456');
INSERT INTO CUSTOMERCITY (CITYNAME, PINCODE) VALUES ('TOWN2','500023');
INSERT INTO CUSTOMERCITY (CITYNAME, PINCODE) VALUES ('VILLAGE1','505639');
INSERT INTO CUSTOMERCITY (CITYNAME, PINCODE) VALUES ('VILLAGE2','505327');

SELECT * FROM CUSTOMERCITY