--Start using SUBASHAGENCIES Database
USE SUBASHAGENCIES

--Drop CUSTOMERCITY table to recreate it using new design
DROP TABLE CUSTOMER_CITY;

--Create CUSTOMERCITY table.
CREATE TABLE CUSTOMER_CITY(
CITYID INT IDENTITY(1,1),
CITYNAME VARCHAR(MAX) NOT NULL,
PINCODE VARCHAR(MAX) NOT NULL,
UPDATED_ON DATE,
CONSTRAINT PK_CUSTOMER_CITY_CITYID PRIMARY KEY CLUSTERED (CITYID));

--Insert records into CUSTOMERCITY table
INSERT INTO CUSTOMER_CITY (CITYNAME, PINCODE) VALUES ('TOWN1','500456');
INSERT INTO CUSTOMER_CITY (CITYNAME, PINCODE) VALUES ('TOWN2','500023');
INSERT INTO CUSTOMER_CITY (CITYNAME, PINCODE) VALUES ('VILLAGE1','505639');
INSERT INTO CUSTOMER_CITY (CITYNAME, PINCODE) VALUES ('VILLAGE2','505327');


--Show inserted records.
SELECT * FROM CUSTOMER_CITY