--Start using SUBASHAGENCIES Database
USE SUBASHAGENCIES

--Drop CUSTOMERBEAT table to recreate it with updated design
DROP TABLE CUSTOMER_BEAT

--Create CUSTOMERBEAT table
CREATE TABLE CUSTOMER_BEAT(
BEATID INT IDENTITY(1,1),
BEATNAME VARCHAR(MAX) NOT NULL,
OUTLET_COUNT INT NOT NULL,
EMPLOYEEID INT,
UPDATED_ON DATE,
CONSTRAINT PK_CUSTOMER_BEAT_BEATID PRIMARY KEY CLUSTERED (BEATID))

-- Insert records into CUSTOMERBEAT table.
INSERT INTO CUSTOMER_BEAT (BEATNAME, OUTLET_COUNT) VALUES ('BEAT1', 50);
INSERT INTO CUSTOMER_BEAT (BEATNAME, OUTLET_COUNT) VALUES ('BEAT2', 50);
INSERT INTO CUSTOMER_BEAT (BEATNAME, OUTLET_COUNT) VALUES ('BEAT3', 50);
INSERT INTO CUSTOMER_BEAT (BEATNAME, OUTLET_COUNT) VALUES ('BEAT4', 50);

--Show inserted records.
SELECT * FROM CUSTOMER_BEAT