CREATE TABLE CUSTOMERSTATUS(
STATUSID INT IDENTITY(1,1),
STATUSCODE VARCHAR(MAX) NOT NULL,
CONSTRAINT PK_CUSTOMERSTATUS_STATUSID PRIMARY KEY CLUSTERED (STATUSID));

--DROP TABLE CUSTOMERSTATUS;

INSERT INTO CUSTOMERSTATUS (STATUSCODE) VALUES ('ACTIVE');
INSERT INTO CUSTOMERSTATUS (STATUSCODE) VALUES ('INACTIVE');

SELECT * FROM CUSTOMERSTATUS