--Use SUBASHAGENCIES Database
USE SUBASHAGENCIES

--Drop CUSTOMER_MASTER table and recreate it using the updated design
DROP TABLE CUSTOMER_MASTER

--Create CUSTOMER_MASTER table using the design provided
CREATE TABLE CUSTOMER_MASTER
(CUSTOMERID INT IDENTITY(1,1), 
CUSTOMER_NAME VARCHAR(100) NOT NULL, 
OUTLET_NAME VARCHAR(100) NOT NULL, 
CATEGORYID INT, 
TYPEID INT, 
BEATID INT, 
ADDRESS1 VARCHAR(80), 
ADDRESS2 VARCHAR(80), 
LANDLINE VARCHAR(15), 
MOBILE VARCHAR(10), 
EMAIL_ADDRESS VARCHAR(80), 
OTHER_DETAILS VARCHAR(80), 
CITYID INT, 
STATUSID INT DEFAULT(1), 
UPDATED_ON DATE, 
CONSTRAINT PK_CUSTOMER_MASTER_CUSTOMERID PRIMARY KEY CLUSTERED (CUSTOMERID))

--Show the records
SELECT * FROM CUSTOMER_MASTER
