CREATE TABLE CUSTOMERCATEGORY(
CATEGORYID INT IDENTITY(1,1),
CATEGORYNAME VARCHAR(MAX) NOT NULL,
CONSTRAINT PK_CUSTOMERCATEGORY_CATEGORYID PRIMARY KEY CLUSTERED (CATEGORYID));

--DROP TABLE CUSTOMERCATEGORY;

INSERT INTO CUSTOMERCATEGORY(CATEGORYNAME) VALUES ('WHOLESALE');
INSERT INTO CUSTOMERCATEGORY(CATEGORYNAME) VALUES ('RETAIL');

SELECT * FROM CUSTOMERCATEGORY;