-- Start using SUBASHAGENCIES Database
USE SUBASHAGENCIES

--Drop CUSTOMERTYPE table to recreate it with updated design
DROP TABLE CUSTOMER_TYPE

--Create CUSTOMERTYPE table.
CREATE TABLE CUSTOMER_TYPE(
TYPEID INT IDENTITY(1,1), 
TYPENAME VARCHAR(MAX) NOT NULL,
UPDATED_ON DATE,
CONSTRAINT PK_CUSTOMER_TYPE_TYPEID PRIMARY KEY CLUSTERED (TYPEID));

--Insert records into CUSTOMERTYPE table.
INSERT INTO CUSTOMER_TYPE (TYPENAME) VALUES ('BAKERY');
INSERT INTO CUSTOMER_TYPE (TYPENAME) VALUES ('GENERAL STORES');
INSERT INTO CUSTOMER_TYPE (TYPENAME) VALUES ('KIRANA MERCHANT');
INSERT INTO CUSTOMER_TYPE (TYPENAME) VALUES ('MEDICAL STORES');

--Show inserted records.
SELECT * FROM CUSTOMER_TYPE;