CREATE TABLE CUSTOMERBEAT(
BEATID INT IDENTITY(1,1),
BEATNAME VARCHAR(MAX) NOT NULL,
CONSTRAINT PK_CUSTOMERBEAT_BEATID PRIMARY KEY CLUSTERED (BEATID))

--DROP TABLE CUSTOMERBEAT

INSERT INTO CUSTOMERBEAT (BEATNAME) VALUES ('BEAT1');
INSERT INTO CUSTOMERBEAT (BEATNAME) VALUES ('BEAT2');
INSERT INTO CUSTOMERBEAT (BEATNAME) VALUES ('BEAT3');
INSERT INTO CUSTOMERBEAT (BEATNAME) VALUES ('BEAT4');

SELECT * FROM CUSTOMERBEAT