--Use SUBASHAGENCIES Database
USE SUBASHAGENCIES;

--Drop EMPLOYEE_DESIGNATION table to recreate using the updated design
DROP TABLE EMPLOYEE_DESIGNATION;

--Create EMPLOYEE_DESIGATION table using the design provided
CREATE TABLE EMPLOYEE_DESIGNATION(
DESIGNATIONID INT IDENTITY(1,1),
DESIGNATIONNAME VARCHAR(MAX) NOT NULL,
UPDATED_ON DATE,
CONSTRAINT PK_EMPLOYEE_DESIGNATIONID_PK PRIMARY KEY CLUSTERED (DESIGNATIONID));

--Insert records into table
INSERT INTO EMPLOYEE_DESIGNATION(DESIGNATIONNAME) VALUES ('SALESMAN');
INSERT INTO EMPLOYEE_DESIGNATION(DESIGNATIONNAME) VALUES ('ACCOUNTANT');
INSERT INTO EMPLOYEE_DESIGNATION(DESIGNATIONNAME) VALUES ('COMPUTER-OPERATOR');
INSERT INTO EMPLOYEE_DESIGNATION(DESIGNATIONNAME) VALUES ('MANAGING-DIRECTOR');

--Show inserted records
SELECT * FROM EMPLOYEE_DESIGNATION;