CREATE TABLE SALESMAN_MASTER(
SALESMANID INT IDENTITY (1,1),
SALESMAN_NAME VARCHAR(MAX),
START_DATE DATE,
END_DATE DATE,
CONSTRAINT SALESMAN_MASTER_PRIMARY_KEY PRIMARY KEY CLUSTERED (SALESMANID))


DROP TABLE SALESMAN_MASTER

