--Use SUBASHAGENCIES Database
USE SUBASHAGENCIES

--Drop table to recreate using the updated design provided
DROP TABLE STATUS

--Create STATUS table
CREATE TABLE STATUS(
STATUSID INT IDENTITY(1,1),
STATUSCODE VARCHAR(MAX) NOT NULL,
UPDATED_ON DATE,
CONSTRAINT PK_STATUS_STATUSID PRIMARY KEY CLUSTERED (STATUSID));

--DROP TABLE CUSTOMERSTATUS;

INSERT INTO STATUS (STATUSCODE) VALUES ('ACTIVE');
INSERT INTO STATUS (STATUSCODE) VALUES ('INACTIVE');

--show records
SELECT * FROM STATUS